// Auto-generated by ops/generate_webapp_config.py — do not edit manually
const STRATEGY_CONFIG = {
  "serverTimeNote": "Toutes les heures sont en heure serveur MT5 (broker).",
  "xauusdCoordination": {
    "enabled": true,
    "strategyKeys": [
      "xauusd",
      "gold"
    ],
    "magics": [
      2026200,
      2026300
    ]
  },
  "riskByStrategyKey": {
    "nas100": 0.5,
    "xauusd": 0.5,
    "eurusd": 1.0,
    "gold": 1.0
  },
  "strategies": {
    "nas100": {
      "label": "NAS100 SMC",
      "icon": "🤖",
      "riskPercent": 0.5,
      "allowedHours": [
        0,
        1,
        2,
        3,
        4,
        7,
        8,
        9,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        20,
        23
      ],
      "hourMode": "server_banned"
    },
    "xauusd": {
      "label": "XAUUSD SMC",
      "icon": "🥇",
      "riskPercent": 0.5,
      "allowedHours": [
        0,
        3,
        4,
        5,
        6,
        8,
        9,
        13,
        14,
        15,
        16,
        17,
        18,
        23
      ],
      "hourMode": "server_banned"
    },
    "eurusd": {
      "label": "EURUSD Trend",
      "icon": "📈",
      "riskPercent": 1.0,
      "allowedHours": [
        6,
        12,
        13,
        15,
        18,
        20
      ],
      "hourMode": "server_allowed"
    },
    "gold": {
      "label": "GOLD Trend",
      "icon": "🏆",
      "riskPercent": 1.0,
      "allowedHours": [
        1,
        3,
        5,
        6,
        7,
        8,
        9,
        14,
        16,
        17,
        20,
        21,
        23
      ],
      "hourMode": "server_allowed"
    }
  }
};
